services:
  user-service:
    image: angeloalcaraz/user-service:latest
    container_name: user-service
    ports:
      - "${PORT_USER_SERVICE}:3000"
    env_file:
      - .env

  favorites-service:
    image: angeloalcaraz/favorites-service:latest
    container_name: favorites-service
    ports:
      - "${PORT_FAVORITES_SERVICE}:3001"
    env_file:
      - .env
    command: ["node", "dist/main.js"]

  favorites-processor:
    image: angeloalcaraz/favorites-service:latest
    container_name: favorites-processor
    env_file:
      - .env
    command: ["node", "dist/queues/favorites-queue-processor.js"]
