services:
  user-service:
    image: angeloalcaraz/user-service:latest
    container_name: user-service
    ports:
      - "${PORT_USER_SERVICE}:3000"
    env_file:
      - .env
    environment:
      PORT: ${PORT_USER_SERVICE}

  favorites-service:
    image: angeloalcaraz/favorites-service:latest
    container_name: favorites-service
    ports:
      - "${PORT_FAVORITES_SERVICE}:3001"
    env_file:
      - .env
    environment:
      PORT: ${PORT_FAVORITES_SERVICE}
